// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservasWEB2.Data;

#nullable disable

namespace ReservasWEB2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610225118_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservasWEB2.Models.Cancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioPorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Canchas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Cancha de césped sintético de última generación con iluminación LED nocturna, camerinos y zona de descanso. Capacidad para 10 jugadores.",
                            Nombre = "Cancha Fútbol 5 — El Clásico",
                            PrecioPorHora = 80000.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cancha amplia con graderías para espectadores, cesped de alta calidad y sistema de riego automático. Ideal para torneos y partidos semi-profesionales.",
                            Nombre = "Cancha Fútbol 7 — La Arena",
                            PrecioPorHora = 120000.00m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cancha techada con piso laminado especial para microfútbol. Disponible los 365 días del año sin importar el clima. Vestuarios y baños incluidos.",
                            Nombre = "Microfútbol Cubierta — El Refugio",
                            PrecioPorHora = 60000.00m
                        });
                });

            modelBuilder.Entity("ReservasWEB2.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ReservasWEB2.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@canchas.com",
                            Nombre = "Administrador",
                            PasswordHash = "$2a$11$AfoWYGLWrrWQtqszjX7iy.2fHcpmsFMDnl4n7QfWvmV4KfbKq2thS",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cliente@canchas.com",
                            Nombre = "Carlos Rodríguez",
                            PasswordHash = "$2a$11$r2yrTOydR/mEzcLe/7u4T.Gw38ESHd3krvTB.wpBxz8Xzb/T.bIfq",
                            Role = "Cliente"
                        });
                });

            modelBuilder.Entity("ReservasWEB2.Models.Reserva", b =>
                {
                    b.HasOne("ReservasWEB2.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasWEB2.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
